repos:
-   repo: local
    hooks:
    -   id: print_statements
        name: Check for print statements
        types: [python]
        entry: 'print\(.*?\)(?!.*# functional)'
        language: pygrep
    -   id: show_statements
        name: Check for show statements
        types: [python]
        entry: '\.show\(.*\)'
        language: pygrep

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        exclude: "tests/.*"

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--max-line-length, "120", "--extend-exclude=tests/**", "--extend-ignore=E501 cishouseholds/pipieline/regex_testing.py"]

-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        args: [--line-length, "120"]
        additional_dependencies: ['click==8.0.1']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.981'
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-setuptools]
